sudo: false

language: node_js

node_js:
  - "6"

addons:
  rethinkdb: '2.3'

cache:
  yarn: true
  directories:
    - node_modules

install:
  - npm install

script:
  - npm run webpack:prod
  - npm run test
